no panic logger
EternisAI/tlsn pull request #10
Opened 2024-10-16 22:34 UTC by asa93

wasm code was panicking if it was attempted to init several times which is not a critical issue

it created an error display that was scary on extension side

little change to fix it

2024-10-16 23:38 UTC, saberistic requested changes
minor cleanup

2024-10-16 23:38 UTC, saberistic commented on crates/wasm/Cargo.toml
> +regex = "1.11.0"
is this part of this PR? I have this library included in the other PR

2024-10-16 23:38 UTC, saberistic commented on crates/wasm/src/lib.rs
> +    fn test_regex() {
is this a playground test? doesn't look like testing functions of the file

2024-10-17 01:51 UTC, asa93 commented on crates/wasm/Cargo.toml
> +regex = "1.11.0"
removed

2024-10-17 01:51 UTC, asa93 commented on crates/wasm/src/lib.rs
> +    fn test_regex() {
removed

2024-10-17 21:27 UTC, asa93 commented
changed made !

2024-10-17 21:29 UTC, merged