Remote Providers
EternisAI/tlsn pull request #9
Opened 2024-10-15 16:14 UTC by saberistic

2024-10-17 22:01 UTC, PratyushRT requested changes
Currently, regex patterns and JMESPath expressions are compiled every time they're needed, which can impact performance. Let's compile these patterns once during the initialization of the Provider struct and store them for reuse. This will improve performance by avoiding redundant compilations.

Here's what I'm thinking:

**Implementation:**

* **Modify the `Provider` struct to include compiled fields:**

```rust
use jmespath::Expression;
use regex::Regex;

pub struct Provider {
    // Existing fields...
    compiled_url_regex: Regex,
    compiled_attributes: Option<Vec<Expression<'static>>>,
    // ...other fields
}
```

* **Update the `Provider::new` method to compile and store these expressions:**

```rust
impl Provider {
    pub fn new(
        id: u32,
        host: &str,
        url_regex: &str,
        target_url: &str,
        method: &str,
        title: &str,
        description: &str,
        icon: &str,
        response_type: &str,
        attributes: Option<&Vec<String>>,
        preprocess: Option<&String>,
    ) -> Self {
        let compiled_url_regex = Regex::new(url_regex).expect("Invalid regex pattern");
        let compiled_attributes = attributes.map(|attrs| {
            attrs
                .iter()
                .filter(|attr| !attr.is_empty())
                .map(|attr| jmespath::compile(attr).expect("Invalid JMESPath expression"))
                .collect()
        });

        Self {
            id,
            host: host.to_string(),
            url_regex: url_regex.to_string(),
            target_url: target_url.to_string(),
            method: method.to_string(),
            title: title.to_string(),
            description: description.to_string(),
            icon: icon.to_string(),
            response_type: response_type.to_string(),
            attributes: attributes.cloned(),
            preprocess: preprocess.cloned(),
            compiled_url_regex,
            compiled_attributes,
        }
    }
}
```

* **Update methods to use the compiled patterns:**

```rust
impl Provider {
    pub fn check_url_method(&self, url: &str, method: &str) -> bool {
        self.compiled_url_regex.is_match(url) && self.method == method
    }

    pub fn get_attributes(&self, response: &serde_json::Value) -> Vec<String> {
        let mut result = Vec::new();
        if let Some(compiled_attributes) = &self.compiled_attributes {
            for expr in compiled_attributes {
                let search_result = expr
                    .search(response)
                    .expect("Failed to execute JMESPath search");
                result.push(search_result.to_string());
            }
        }
        result
    }
}
```

2024-10-17 22:01 UTC, PratyushRT commented on crates/verifier/src/provider.rs
There are avoidable clones of data structures, especially in loops and method calls, which can affect performance. Let's use references and borrow data where possible to avoid unnecessary clones.


* **In `Processor::new`, iterate over references to provider configurations:**

```rust
for provider_config in &config_json.providers {
    // Use provider_config directly without cloning
}
```

* **In `Provider::new`, accept references instead of owned values:**

```rust
impl Provider {
    pub fn new(
        id: u32,
        host: &str,
        url_regex: &str,
        target_url: &str,
        method: &str,
        title: &str,
        description: &str,
        icon: &str,
        response_type: &str,
        attributes: Option<&Vec<String>>,
        preprocess: Option<&String>,
    ) -> Self {
        let compiled_url_regex = Regex::new(url_regex).expect("Invalid regex pattern");
        let compiled_attributes = attributes.map(|attrs| {
            attrs
                .iter()
                .filter(|attr| !attr.is_empty())
                .map(|attr| jmespath::compile(attr).expect("Invalid JMESPath expression"))
                .collect()
        });

        Self {
            id,
            host: host.to_string(),
            url_regex: url_regex.to_string(),
            target_url: target_url.to_string(),
            method: method.to_string(),
            title: title.to_string(),
            description: description.to_string(),
            icon: icon.to_string(),
            response_type: response_type.to_string(),
            attributes: attributes.cloned(),
            preprocess: preprocess.cloned(),
            compiled_url_regex,
            compiled_attributes,
        }
    }
}
```

* **Pass references when calling `Provider::new`:**

```rust
let provider = Provider::new(
    provider_config.id,
    &provider_config.host,
    &provider_config.url_regex,
    &provider_config.target_url,
    &provider_config.method,
    &provider_config.title,
    &provider_config.description,
    &provider_config.icon,
    &provider_config.response_type,
    provider_config.attributes.as_ref(),
    provider_config.preprocess.as_ref(),
);
```

2024-10-17 22:04 UTC, saberistic commented
Any concern about the fact that notary loads the config once and updating providers required notary restart? Is this an accepted behavior?

2024-10-17 22:11 UTC, PratyushRT commented
Fair point, lets think about it carefully, could be okay if its done at a low-usage time but also might not be worth it depending on the factor improvement

2024-10-17 22:46 UTC, saberistic commented
@PratyushRT there is issue with compiling JMESPath and Regex since this config is stored in Notary Global and it should be shared between threads neither of this objects implement a thread safe sync trait, observed error:
```
error[E0277]: `Rc<jmespath::variable::Variable>` cannot be shared between threads safely
   --> crates/notary/server/src/service.rs:128:28
    |
128 |     State(notary_globals): State<NotaryGlobals>,
    |                            ^^^^^ `Rc<jmespath::variable::Variable>` cannot be shared between threads safely
```

2024-10-18 07:57 UTC, saberistic commented on crates/verifier/src/provider.rs
since JMESPath is. not thread safe I introduced two cache per thread, attributed and regex, then save the compile resources by the provider ID in those caches on first call

2024-10-18 07:58 UTC, saberistic commented on crates/verifier/src/provider.rs
latest commit addressed this, we don't need to have a new function anymore and deserializing json is sufficient

2024-10-18 08:00 UTC, saberistic commented on crates/verifier/src/provider.rs
this is addressed in latest commit

2024-10-18 17:06 UTC, PratyushRT commented
@saberistic  An alternative solution to address the thread safety issue with jmespath expressions I was going to look into myself was to look for a thread safety feature provided by the jmespath crate. And then using this so that the crate switches from using `Rc` to `Arc`, allowing compiled expressions to be safely shared across threads without additional caching mechanisms.

Can not really find such a feature in version 0.3.0 of the jmespath crate, so your approach of using thread-local storage here is a practical and effective solution.

2024-10-18 17:07 UTC, PratyushRT approved these changes

2024-10-21 15:26 UTC, saberistic commented on crates/verifier/src/provider.rs
> +mod tests {
retried the tests and they are passing, please provide more details

<img width="626" alt="image" src="https://github.com/user-attachments/assets/5d13bbe2-d96d-47a9-9358-f6184984ad50">

2024-10-21 15:27 UTC, saberistic commented on crates/verifier/src/provider.rs
> +pub struct Processor {
open to suggestions

2024-10-21 15:28 UTC, saberistic commented on crates/verifier/src/provider.rs
> +#[cfg(feature = "provider")]
certain modules used here are not wasm compatible, I used a feature to mask them when wasm module uses this crate

2024-10-21 15:32 UTC, saberistic commented on crates/verifier/src/provider.rs
> +                Err(e) => {
good catch, commited a change to reflect it

2024-10-25 19:37 UTC, asa93 commented on crates/verifier/src/provider.rs
> +pub struct Processor {
it's just processing provider no ?

2024-10-25 20:51 UTC, merged